### ISSUE TITLE
Images not Showing, But Are Linked

### ISSUE THREAD

**Issue by arjwright** [cleverdevil/microgram#1]
Noticed that images are not loading on site (
http://www.avancee.agency/scribbles/), however CSS effects and the links to the images are showing.

Moved CSS to the Micro.Blog custom CSS to see if that was the issue initially. That did not merit any change. 

Also looked at my device settings (iOS Safari, using 1Blocker); changed to allow Microgram domain to whitelist but also no change.

**Comment by cleverdevil** [comment]
It looks like things are working now. What was the issue?

**Comment by arjwright** [comment]
Looks like is now working as well; not sure what might have been the case. You can go ahead and close this; if it comes up again, I’ll be sure to put another issue here.
